# uegCCD Test Suite

This directory contains multiple test cases for uegCCD, each in their own directory. It also contains the Python module `uegccdutils` which is used for loading uegCCD output files for regression testing. *In future this directory could become its own repository.*

## Setting up the Testing Environment
1. Assuming you are using Conda, create a new environment for `uegccdutils` using `conda env create -f test-environment.yml`.
2. Activate your new testing environment with `conda activate uegccd-testing`
3. Install `uegccdutils` by running `pip install uegccdutils/`
    * If you plan to develop `uegccdutils`, add the `-e` (editable) flag to the `install` subcommand.

## Running the Test Suite

The test suite can be run by executing commands within this `testing/` directory.

1. Execute all tests with `./run_tests.sh`
2. With the `uegccd-testing` environment active, run `pytest`

## Adding New Tests

### Testing Additional Input Files

Each test directory should contain, at minimum:
* the test's `Input` file
* a Python script for executing regression testing on the results. 
The name of this script should follow the pattern `test_<dirname>.py`.
* a directory of test results generated by `pytest`

To add a new combination of input parameters to the test suite, perform the following steps:
1. Create a new directory inside `testing/` to contain your new test.
2. Add your `Input` file & the `test_<dirname.py>` script to this new directory. Code for a simple regression test can be found in a later section.
3. Add your new directory to the directory list in the `run_tests.sh` script. Execute the script to confirm it's been added. 
4. Run `pytest`. You will get an error for your new test directory that says "Failed: File not found in data directory, created:" which you can safely ignore. A new subdirectory has been created containing your reference output. If you run `pytest` again, you should see that all tests pass.
5. Commit your new test directory (including reference data) to GitHub.

### Regression Testing New Quantities

If you have additional uegCCD functionality that you want to regression test, you'll have to update `uegccdutils`. Specifically, you'll have to
add the values you want to regression test to the dictionary returned by the
`test_summary` method of the `Dataset` class in `load.py`.
As seen in the example test script below, this is the only method used for simple regression testing. You are welcome to add your own kinds of more sophisticated testing if you desire.

Once you have added the new quantity you want to test, run `pytest --regen-all`
to regenerate all of the reference data. **Make sure to commit this new reference data to GitHub!**

If you're looking to regression test more quantities, it's likely you have either modified an existing uegCCD output file or created a new one. To read a new file, define a new method for the `Dataset` class in `load.py`; for example, `_load_fort00`. These method names should start with leading underscores to keep them private; individual load functions should not be executed by the user. Instead, call your new load method inside the main `__init__` method alongside the other output parsing functions. **If you did not install `uegccdutils` in editable mode with the `-e` flag, reinstall the module.**

### Example Test Script

This script executes a basic regression test that can be copied for any test case. Make sure the filename matches the pattern `test_<dirname>.py`.

```python
import os
import pytest
import numpy as np
from uegccdutils import Dataset

dir = os.path.basename(__file__)[5:-3] # infer directory from test name

def test_output(data_regression):
	data = Dataset(dir).test_summary()
	data_regression.check(data)

def test_fort80_consistency():
	data = Dataset(dir)
	for fctr in data.structure_factors:
		sum = fctr["exchange S(G)"] \
			+ fctr["non-exchange S(G)"]
		assert np.allclose(sum, fctr["S(G)"])

```